PROMPT_COMMAND='USER=$(oc config view -o jsonpath="{.current\-context}" | awk -F/ '"'"'{print $3}'"'"' | sed -s "s/system:serviceaccount/sa/");\
    PROJECT=$(oc config view -o jsonpath="{.current\-context}" | awk -F/ '"'"'{print $1}'"'"');\
PS1="[$USER/$PROJECT  \u \W]\$ "'
